// The write-up rendered at /gameday/methodology, via the shared RecapBody markdown renderer
// (see app/ui/recap-body.tsx). Kept as data (an array of lines, not a single template literal
// -- the content itself is full of markdown backticks, which would prematurely close a
// backtick-delimited JS template string) rather than inline JSX, so it reads and is edited as
// prose/notation, not markup -- same reasoning as recap bodies.
//
// Notation is plain Unicode in inline code spans (e.g. `τ`, `λ_i`, `σ_M`) rather than LaTeX --
// RecapBody's react-markdown pipeline has no math renderer wired in (just remark-gfm), and
// adding remark-math/rehype-katex plus KaTeX's CSS for one documentation page wasn't worth the
// new dependency. Code-span notation is a completely standard way to present formulas in plain
// prose and needs nothing beyond what RecapBody already renders.
const LINES = [
  "## Overview",
  "",
  "Every pick on the GameDay dashboard that hasn't been officially graded yet — pregame,",
  "in-progress, or just-finished-but-not-yet-graded — shows a live estimate of Pr(pick wins).",
  "Pregame, that's derived from the market's own current price (see the dedicated Pregame",
  "section below); once there's an actual score, it's the team-pace projection Steps 1-4",
  "derive. The implementation is `app/lib/live-projection.ts` if you'd rather read code than",
  "prose; the notation below maps onto it more or less 1:1.",
  "",
  "The model is intentionally simple: two independent normal random variables, a credibility",
  "estimator you'll recognize immediately, and a standard Pr(X > c) tail calculation. No",
  "possession state, no play-by-play, no in-game pace signal. That's a deliberate scope decision,",
  "not an oversight — see **Known limitations** below for the reasoning, and **Where we'd like",
  "help** if you want to push on it.",
  "",
  "## Notation",
  "",
  "| Symbol | Meaning |",
  "| --- | --- |",
  "| `t` | Elapsed game time (minutes) |",
  "| `τ` | Minutes remaining in regulation, `τ = 60 − t` (undefined in overtime — see below) |",
  "| `S_H(t)`, `S_A(t)` | Current home / away score |",
  "| `n_i` | Games team *i* has played this season with a final score on record |",
  "| `X̄_i` | Team *i*'s season-to-date average points per game |",
  "| `μ` | League-wide average points per game, pooled across every final game logged this season (falls back to a fixed 22.5 if literally none exist yet, e.g. Week 1 pregame) |",
  "| `k` | Credibility parameter, currently **4** (games) |",
  "| `λ̂_i` | Team *i*'s blended projected scoring rate, points/minute |",
  "| `σ` | Full-game (60-minute) single-team scoring standard deviation, currently a fixed **10** |",
  "| `R_H`, `R_A` | Random variables for each team's *remaining* points from now to end of regulation |",
  "| `Φ` | Standard normal CDF |",
  "| `Φ⁻¹` | Inverse standard normal CDF (probit function) — used only pregame, see below |",
  "| `L`, `L'` | A posted line (spread or total) — locked (pool's grading line) vs. live (current market), respectively |",
  "| `o` | American odds for one side of a market (e.g. `-118`) |",
  "",
  "## Step 1 — Scoring rate via credibility weighting",
  "",
  "Each team's projected scoring rate is a straight Bühlmann-style credibility estimate between",
  "its own season-to-date average and the league mean:",
  "",
  "```",
  "Z_i  = n_i / (n_i + k)",
  "λ̂_i = [ Z_i · X̄_i + (1 − Z_i) · μ ] / 60",
  "```",
  "",
  "`Z_i` is the credibility factor: a team with zero games logged this season gets `Z_i = 0`",
  "(100% league average); by `n_i = k = 4` games, its own sample carries half the weight; well",
  "beyond that, `λ̂_i` is mostly the team's own number. This is exactly the standard",
  "credibility-weighted-average construction — `k` is the \"how many games until I trust your own",
  "data\" knob, chosen at 4 somewhat arbitrarily and not (yet) fit to anything.",
  "",
  "**Deliberately not included in `λ̂_i`: today's own in-game pace.** An earlier version of this",
  "discussion considered blending in the current game's actual scoring rate, weighted by elapsed",
  "time. We dropped it — a team that's run unusually hot or cold *so far today* tends to see that",
  "invert going forward (garbage-time scoring once a game is out of reach; a leading team killing",
  "clock and running more), so extrapolating today's pace forward would systematically mislead",
  "rather than help. `λ̂_i` is fixed once computed and does not update from the live game.",
  "",
  "## Step 2 — Distribution of remaining points",
  "",
  "Treating scoring as accruing at an approximately constant rate with roughly homogeneous,",
  "independent increments over disjoint time intervals — the same structural assumption behind",
  "modeling aggregate claims over sub-periods of an exposure period — remaining points for each",
  "team is approximately normal by a CLT-style argument:",
  "",
  "```",
  "R_i ~ N( λ̂_i · τ,  σ² · τ / 60 )",
  "```",
  "",
  "The mean scales linearly in `τ` (constant rate). The **variance also scales linearly in",
  "`τ`** under the same independent-increments assumption — identical to how variance",
  "accumulates linearly under Brownian motion, or how aggregate-loss variance scales with",
  "exposure time under a compound process with constant intensity. `σ` itself is a single fixed",
  "constant (10), not team-specific, not weather- or pace-adjusted, not yet fit to this league's",
  "own data — see limitations.",
  "",
  "**Pregame does NOT use this distribution at all.** An earlier version ran the same",
  "`R_i ~ N(λ̂_i·τ, σ²·τ/60)` machinery pregame too, with `τ = 60` and `S_H(t) = S_A(t) = 0`. A",
  "live check against real market odds (see Validation) showed that overconfident — with only",
  "a couple games of season data, `λ̂_i` leans heavily on the league average, which doesn't",
  "reflect the specific matchup, and that bias compounds for totals (both teams' pace errors",
  "add) rather than canceling (as they mostly do for a margin). Pregame now uses the market's",
  "own live price instead — see the **Pregame** section after Step 4. Steps 1-4 below describe",
  "the in-game model only; they start being used once there's an actual score to project from.",
  "",
  "## Step 3 — Projected final margin / total",
  "",
  "Let `Ŝ_H = S_H(t) + R_H` and `Ŝ_A = S_A(t) + R_A` be the projected final scores. Assuming",
  "`R_H ⟂ R_A` (independence — see limitations), and since a linear combination of independent",
  "normals is itself normal:",
  "",
  "**Margin** (for spread picks), `M = Ŝ_H − Ŝ_A`:",
  "",
  "```",
  "M ~ N( μ_M, σ_M² ),  where",
  "μ_M  = [S_H(t) − S_A(t)] + (λ̂_H − λ̂_A) · τ",
  "σ_M² = Var(R_H) + Var(R_A) = σ² · τ / 30",
  "```",
  "",
  "**Total** (for over/under picks), `T = Ŝ_H + Ŝ_A`, has the *same* variance as `M` —",
  "Var(X+Y) = Var(X−Y) = Var(X) + Var(Y) for independent X, Y — with mean",
  "`μ_T = [S_H(t) + S_A(t)] + (λ̂_H + λ̂_A) · τ`.",
  "",
  "## Step 4 — Win probability",
  "",
  "With `Φ` the standard normal CDF (own Abramowitz–Stegun `erf` approximation, no external",
  "library):",
  "",
  "For a **spread** pick, home covers a line `s` (home's own line, sportsbook sign convention —",
  "negative means home favored) iff `M > −s`:",
  "",
  "```",
  "Pr(home covers) = Φ( (μ_M + s) / σ_M )",
  "Pr(away covers) = 1 − Pr(home covers)",
  "```",
  "",
  "For a **total** pick against line `L`:",
  "",
  "```",
  "Pr(over)  = Φ( (μ_T − L) / σ_T )",
  "Pr(under) = 1 − Pr(over)",
  "```",
  "",
  "Whichever side matches the participant's actual pick is what the dashboard displays.",
  "",
  "## Pregame — re-anchoring the market's live price",
  "",
  "Pregame there's no score to project from, and — per the Validation finding above — no good",
  "reason to trust our own team-pace projection over the market's. But the pool's own locked",
  "line `L` (frozen at whatever it was when it locked, typically Tuesday) can drift from where",
  "the live market `L'` currently sits, and a participant is graded against `L`, not `L'`. This",
  "section derives a probability for `L` from `L'`'s current live price, rather than assuming a",
  "flat 50%.",
  "",
  "**De-vig the live price.** American odds `o` convert to a raw (vig-included) implied",
  "probability:",
  "",
  "```",
  "p(o) = -o / (-o + 100)   if o < 0",
  "p(o) =  100 / (o + 100)  if o > 0",
  "```",
  "",
  "For two-sided odds `o_A`, `o_B` on the same market (e.g. home spread price vs. away spread",
  "price), `p(o_A) + p(o_B) > 1` — that excess is the sportsbook's vig. Removing it",
  "proportionally gives the standard de-vig estimate:",
  "",
  "```",
  "p_live = p(o_A) / ( p(o_A) + p(o_B) )",
  "```",
  "",
  "**Recover an implied mean, and re-evaluate at `L`.** Modeling the eventual margin (or total)",
  "as `N(μ, σ_M²)` with the same full-game `σ_M = σ√2` Step 2 uses (all 60 minutes still",
  "ahead), `p_live` is itself `Φ` evaluated at `L'`. Inverting:",
  "",
  "```",
  "μ = Φ⁻¹(p_live) · σ_M − L'        (spread; margin sign convention as in Step 4)",
  "μ = Φ⁻¹(p_live) · σ_M + L'        (total)",
  "```",
  "",
  "and then evaluating that same `μ` at the pool's own `L` gives the probability the dashboard",
  "actually shows:",
  "",
  "```",
  "Pr(covers L) = Φ( (μ + L) / σ_M )   (spread)",
  "Pr(over L)   = Φ( (μ − L) / σ_M )   (total)",
  "```",
  "",
  "When `L = L'` (the common case — the number rarely moves once posted; the *price* moves",
  "constantly as money comes in), this collapses to exactly `p_live` with no distortion. When",
  "they've diverged, it re-anchors correctly. If live pricing isn't available for a game (e.g.",
  "before this feature's own first sync populates it), the dashboard falls back to a flat 0.5",
  "rather than erroring.",
  "",
  "## Known limitations",
  "",
  "The model is a first cut, not a finished product. In rough order of how much we'd guess each",
  "one matters:",
  "",
  "1. **Independence between `R_H` and `R_A`.** Real games have possession-based structure —",
  "   a scoring drive for one team necessarily ends the other's current possession, and",
  "   pace-of-play (hurry-up, run-heavy clock control) tends to move both teams' scoring",
  "   together. This model ignores all of that.",
  "2. **No game-script / leverage adjustment**, on purpose. Trailing teams take more risk",
  "   (increasing variance, sometimes their own effective rate); leading teams often slow the",
  "   game down. We considered and explicitly rejected building this in, on the grounds that a",
  "   miscalibrated directional adjustment seemed riskier than no adjustment at all. The",
  "   practical cost: the model likely *understates* variance in exactly these high-leverage",
  "   situations, since it has no mechanism for the bursty, high-variance possessions",
  "   (strip-sack returns, onside kicks, two-minute drills) that show up disproportionately when",
  "   a team is trailing.",
  "3. **One global `σ`, not estimated from data.** 10 points is a plausible round number for",
  "   full-game NFL team-score dispersion, not a fitted value — see Validation.",
  "4. **No possession/down-and-distance/red-zone state.** The model only ever looks at the",
  "   scoreboard and the clock.",
  "5. **No overtime handling.** `τ` is undefined once regulation ends without a winner —",
  "   `projectWinProbability` returns `null` and the dashboard falls back to a plain",
  "   current-score-vs.-line comparison instead of a probability.",
  "6. **Continuous approximation of discrete scoring.** Points arrive in lumps of 2, 3, 6, 7, or",
  "   8 — the normal approximation is a relaxation that's reasonable in aggregate over a full",
  "   game but coarser late, when only a possession or two remains.",
  "7. **Pregame depends entirely on one odds provider (whichever ESPN surfaces first by",
  "   priority — currently DraftKings).** No cross-book averaging, so an idiosyncratic price at",
  "   that one book flows straight through.",
  "8. **There's a real discontinuity right at kickoff, not just a theoretical one.** The",
  "   pregame (live-price) and in-game (team-pace) mechanisms are two independent calculations",
  "   with no shared underlying model — they don't converge to each other as kickoff",
  "   approaches, they just get swapped the instant `period` ticks from 0 to 1. Given the team-",
  "   pace model was specifically shown to run high early in the season (see Validation), the",
  "   probability the dashboard shows can visibly jump at the opening kickoff.",
  "",
  "## Validation so far",
  "",
  "Live spot-checks, not a backtest — three so far, in the order they happened:",
  "",
  "**1. In-game (checked out).** A team trailing by 6 with ~21 minutes left needed a 9-point",
  "swing to cover a 3-point spread; the model showed roughly 12%. ESPN's own win-probability",
  "model showed about 20.8% to cover a *1.5*-point spread in a comparable in-game state — a",
  "strictly easier bar to clear than 3 points. Our lower number for the harder line was",
  "directionally consistent with theirs.",
  "",
  "**2. Pregame, team-pace version (didn't check out — this is what changed the model).** A",
  "pregame Over 42.5 total showed 59%. Backing out the vig from the actual market odds (-112",
  "over / -108 under) gives a fair implied probability of about 50.4% — essentially a coin",
  "flip, as a total line should be. The gap traced back to `λ̂_i` leaning on the league average",
  "with only ~2 games of team data logged so far this season, projecting a combined total",
  "(~45.7) well above what this specific matchup's market actually priced. This is what",
  "prompted the live-price re-anchoring described in the Pregame section above.",
  "",
  "**3. Pregame, live-price version (checked out).** Same matchup, spread side: MIN -1.5 priced",
  "at -102, TB +1.5 at -118 — noticeably off a standard -110/-110, i.e. the market had drifted",
  "toward TB covering more often than not. De-vigging gives MIN -1.5 to cover at ~48.3%. Since",
  "the live number matched the pool's own locked number here, the live-price mechanism",
  "reduces to exactly that de-vigged figure with no re-anchoring distortion — which is the",
  "correct, market-consistent answer, unlike the flat 50% the previous version would have shown",
  "for the exact same situation.",
  "",
  "## Where we'd like help",
  "",
  "This model exists to be picked apart by people who do this for a living. Concretely useful",
  "contributions:",
  "",
  "- **A real backtest.** Log every `liveWinProbability` the model emits against the actual",
  "  graded outcome, across a full season of snapshots, and compute a calibration curve / Brier",
  "  score / log-loss. We don't currently persist historical snapshots of the live probability",
  "  anywhere — that'd need to be added first.",
  "- **An empirically-fit `σ`**, ideally split by whether it should vary with time remaining,",
  "  score differential, or team, instead of one fixed constant.",
  "- **A principled correlation structure** between `R_H` and `R_A`, if one can be fit",
  "  without just adding noise.",
  "- **A defensible leverage/game-script adjustment** — if someone can show one that doesn't",
  "  systematically point the wrong direction, we'd rather have it than not.",
  "- **Overtime.**",
  "- **Multi-book averaging for the pregame price**, instead of trusting whichever single",
  "  provider ESPN surfaces first.",
  "- **Smoothing the kickoff discontinuity** (limitation 8) — some principled way to blend the",
  "  live-price and team-pace mechanisms across the transition instead of a hard swap.",
  "",
  "If you find a game state where the number the dashboard shows looks obviously wrong, that's",
  "useful signal even without a fix attached — say so.",
];

export const METHODOLOGY_MARKDOWN = LINES.join("\n");
