// The write-up rendered at /gameday/methodology, via the shared RecapBody markdown renderer
// (see app/ui/recap-body.tsx). Kept as data (an array of lines, not a single template literal
// -- the content itself is full of markdown backticks, which would prematurely close a
// backtick-delimited JS template string) rather than inline JSX, so it reads and is edited as
// prose/notation, not markup -- same reasoning as recap bodies.
//
// Notation is plain Unicode in inline code spans (e.g. `τ`, `λ_i`, `σ_M`) rather than LaTeX --
// RecapBody's react-markdown pipeline has no math renderer wired in (just remark-gfm), and
// adding remark-math/rehype-katex plus KaTeX's CSS for one documentation page wasn't worth the
// new dependency. Code-span notation is a completely standard way to present formulas in plain
// prose and needs nothing beyond what RecapBody already renders.
const LINES = [
  "## Overview",
  "",
  "Every pick on the GameDay dashboard that hasn't been officially graded yet, but whose game",
  "has started, shows a live estimate of Pr(pick wins). This page derives that estimate — the",
  "implementation is `app/lib/live-projection.ts` if you'd rather read code than prose; the",
  "notation below maps onto it more or less 1:1.",
  "",
  "The model is intentionally simple: two independent normal random variables, a credibility",
  "estimator you'll recognize immediately, and a standard Pr(X > c) tail calculation. No",
  "possession state, no play-by-play, no in-game pace signal. That's a deliberate scope decision,",
  "not an oversight — see **Known limitations** below for the reasoning, and **Where we'd like",
  "help** if you want to push on it.",
  "",
  "## Notation",
  "",
  "| Symbol | Meaning |",
  "| --- | --- |",
  "| `t` | Elapsed game time (minutes) |",
  "| `τ` | Minutes remaining in regulation, `τ = 60 − t` (undefined in overtime — see below) |",
  "| `S_H(t)`, `S_A(t)` | Current home / away score |",
  "| `n_i` | Games team *i* has played this season with a final score on record |",
  "| `X̄_i` | Team *i*'s season-to-date average points per game |",
  "| `μ` | League-wide average points per game, pooled across every final game logged this season (falls back to a fixed 22.5 if literally none exist yet, e.g. Week 1 pregame) |",
  "| `k` | Credibility parameter, currently **4** (games) |",
  "| `λ̂_i` | Team *i*'s blended projected scoring rate, points/minute |",
  "| `σ` | Full-game (60-minute) single-team scoring standard deviation, currently a fixed **10** |",
  "| `R_H`, `R_A` | Random variables for each team's *remaining* points from now to end of regulation |",
  "| `Φ` | Standard normal CDF |",
  "",
  "## Step 1 — Scoring rate via credibility weighting",
  "",
  "Each team's projected scoring rate is a straight Bühlmann-style credibility estimate between",
  "its own season-to-date average and the league mean:",
  "",
  "```",
  "Z_i  = n_i / (n_i + k)",
  "λ̂_i = [ Z_i · X̄_i + (1 − Z_i) · μ ] / 60",
  "```",
  "",
  "`Z_i` is the credibility factor: a team with zero games logged this season gets `Z_i = 0`",
  "(100% league average); by `n_i = k = 4` games, its own sample carries half the weight; well",
  "beyond that, `λ̂_i` is mostly the team's own number. This is exactly the standard",
  "credibility-weighted-average construction — `k` is the \"how many games until I trust your own",
  "data\" knob, chosen at 4 somewhat arbitrarily and not (yet) fit to anything.",
  "",
  "**Deliberately not included in `λ̂_i`: today's own in-game pace.** An earlier version of this",
  "discussion considered blending in the current game's actual scoring rate, weighted by elapsed",
  "time. We dropped it — a team that's run unusually hot or cold *so far today* tends to see that",
  "invert going forward (garbage-time scoring once a game is out of reach; a leading team killing",
  "clock and running more), so extrapolating today's pace forward would systematically mislead",
  "rather than help. `λ̂_i` is fixed once computed and does not update from the live game.",
  "",
  "## Step 2 — Distribution of remaining points",
  "",
  "Treating scoring as accruing at an approximately constant rate with roughly homogeneous,",
  "independent increments over disjoint time intervals — the same structural assumption behind",
  "modeling aggregate claims over sub-periods of an exposure period — remaining points for each",
  "team is approximately normal by a CLT-style argument:",
  "",
  "```",
  "R_i ~ N( λ̂_i · τ,  σ² · τ / 60 )",
  "```",
  "",
  "The mean scales linearly in `τ` (constant rate). The **variance also scales linearly in",
  "`τ`** under the same independent-increments assumption — identical to how variance",
  "accumulates linearly under Brownian motion, or how aggregate-loss variance scales with",
  "exposure time under a compound process with constant intensity. `σ` itself is a single fixed",
  "constant (10), not team-specific, not weather- or pace-adjusted, not yet fit to this league's",
  "own data — see limitations.",
  "",
  "## Step 3 — Projected final margin / total",
  "",
  "Let `Ŝ_H = S_H(t) + R_H` and `Ŝ_A = S_A(t) + R_A` be the projected final scores. Assuming",
  "`R_H ⟂ R_A` (independence — see limitations), and since a linear combination of independent",
  "normals is itself normal:",
  "",
  "**Margin** (for spread picks), `M = Ŝ_H − Ŝ_A`:",
  "",
  "```",
  "M ~ N( μ_M, σ_M² ),  where",
  "μ_M  = [S_H(t) − S_A(t)] + (λ̂_H − λ̂_A) · τ",
  "σ_M² = Var(R_H) + Var(R_A) = σ² · τ / 30",
  "```",
  "",
  "**Total** (for over/under picks), `T = Ŝ_H + Ŝ_A`, has the *same* variance as `M` —",
  "Var(X+Y) = Var(X−Y) = Var(X) + Var(Y) for independent X, Y — with mean",
  "`μ_T = [S_H(t) + S_A(t)] + (λ̂_H + λ̂_A) · τ`.",
  "",
  "## Step 4 — Win probability",
  "",
  "With `Φ` the standard normal CDF (own Abramowitz–Stegun `erf` approximation, no external",
  "library):",
  "",
  "For a **spread** pick, home covers a line `s` (home's own line, sportsbook sign convention —",
  "negative means home favored) iff `M > −s`:",
  "",
  "```",
  "Pr(home covers) = Φ( (μ_M + s) / σ_M )",
  "Pr(away covers) = 1 − Pr(home covers)",
  "```",
  "",
  "For a **total** pick against line `L`:",
  "",
  "```",
  "Pr(over)  = Φ( (μ_T − L) / σ_T )",
  "Pr(under) = 1 − Pr(over)",
  "```",
  "",
  "Whichever side matches the participant's actual pick is what the dashboard displays.",
  "",
  "## Known limitations",
  "",
  "The model is a first cut, not a finished product. In rough order of how much we'd guess each",
  "one matters:",
  "",
  "1. **Independence between `R_H` and `R_A`.** Real games have possession-based structure —",
  "   a scoring drive for one team necessarily ends the other's current possession, and",
  "   pace-of-play (hurry-up, run-heavy clock control) tends to move both teams' scoring",
  "   together. This model ignores all of that.",
  "2. **No game-script / leverage adjustment**, on purpose. Trailing teams take more risk",
  "   (increasing variance, sometimes their own effective rate); leading teams often slow the",
  "   game down. We considered and explicitly rejected building this in, on the grounds that a",
  "   miscalibrated directional adjustment seemed riskier than no adjustment at all. The",
  "   practical cost: the model likely *understates* variance in exactly these high-leverage",
  "   situations, since it has no mechanism for the bursty, high-variance possessions",
  "   (strip-sack returns, onside kicks, two-minute drills) that show up disproportionately when",
  "   a team is trailing.",
  "3. **One global `σ`, not estimated from data.** 10 points is a plausible round number for",
  "   full-game NFL team-score dispersion, not a fitted value — see Validation.",
  "4. **No possession/down-and-distance/red-zone state.** The model only ever looks at the",
  "   scoreboard and the clock.",
  "5. **No overtime handling.** `τ` is undefined once regulation ends without a winner —",
  "   `projectWinProbability` returns `null` and the dashboard falls back to a plain",
  "   current-score-vs.-line comparison instead of a probability.",
  "6. **Continuous approximation of discrete scoring.** Points arrive in lumps of 2, 3, 6, 7, or",
  "   8 — the normal approximation is a relaxation that's reasonable in aggregate over a full",
  "   game but coarser late, when only a possession or two remains.",
  "",
  "## Validation so far",
  "",
  "One live spot-check, not a backtest: in a game where a team trailing by 6 with ~21 minutes",
  "left needed a 9-point swing to cover a 3-point spread, the model showed roughly 12%. For",
  "comparison, ESPN's own win-probability model showed about 20.8% to cover a *1.5*-point spread",
  "in a comparable in-game state — a strictly easier bar to clear than 3 points. Our lower number",
  "for the harder line is directionally consistent with theirs, which is some evidence the model",
  "isn't wildly miscalibrated, but it's one data point, not a validation.",
  "",
  "## Where we'd like help",
  "",
  "This model exists to be picked apart by people who do this for a living. Concretely useful",
  "contributions:",
  "",
  "- **A real backtest.** Log every `liveWinProbability` the model emits against the actual",
  "  graded outcome, across a full season of snapshots, and compute a calibration curve / Brier",
  "  score / log-loss. We don't currently persist historical snapshots of the live probability",
  "  anywhere — that'd need to be added first.",
  "- **An empirically-fit `σ`**, ideally split by whether it should vary with time remaining,",
  "  score differential, or team, instead of one fixed constant.",
  "- **A principled correlation structure** between `R_H` and `R_A`, if one can be fit",
  "  without just adding noise.",
  "- **A defensible leverage/game-script adjustment** — if someone can show one that doesn't",
  "  systematically point the wrong direction, we'd rather have it than not.",
  "- **Overtime.**",
  "",
  "If you find a game state where the number the dashboard shows looks obviously wrong, that's",
  "useful signal even without a fix attached — say so.",
];

export const METHODOLOGY_MARKDOWN = LINES.join("\n");
